name: Deploy
on:
  workflow_call:
    inputs:
      is_pr:
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For peaceiris/actions-gh-pages
    steps:
      - uses: actions/checkout@v3.5.3 # v3.5.3
      - name: get nested property
        id: package_json
        uses: notiz-dev/github-action-json-property@v0.2.0 # v0.2.0
        with: 
          path: package.json
          prop_path: volta.node
      - uses: actions/setup-node@v3.8.1 # v3.8.1
        with:
          node-version: ${{steps.package_json.outputs.prop}}
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - uses: peaceiris/actions-gh-pages@v3.9.3 # v3.9.3
        if: "! inputs.is_pr"
        with:
          github_token: ${{ github.token }}
          publish_dir: ./build
          destination_dir: ./docs
